[workspace]
members = [
    "crates/rune",
    "crates/rune-cli",
    "crates/rune-languageserver",
    "crates/rune-macros",
    "crates/rune-modules",
    "crates/rune-wasm",
    "crates/runestick",
    "crates/runestick-macros",
]

exclude = [
    "tools/builder",
    "tools/site",
    "tools/generate",
]
